language: node_js
node_js:
  - '9'
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - google-chrome-stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run test-headless
  - ng build --prod --base-href https://shang-ting.github.io/ngx-hm-calendar/
