language: node_js
node_js:
  - '9'
dist: trusty
addons:
  apt:
    packages:
      - google-chrome-stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run test-headless
  - ng build --prod --base-href https://shang-ting.github.io/ngx-hm-calendar/
